name: Build Mod Stardew Valley

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o mod
        run: dotnet build --configuration Release

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: bin/Release/
